# Generated by Django 5.1 on 2024-12-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_author_alter_book_price_alter_book_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_images/OIP.jpg', upload_to='book_images/'),
        ),
    ]
