# Generated by Django 5.1 on 2024-12-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_images/default.jpg', upload_to='book_images/'),
        ),
    ]
