# Generated by Django 5.1 on 2024-12-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_id_alter_book_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
